### ISSUE TITLE
Sbt warning due to having "org.scala-lang" as organization

### ISSUE THREAD

**Issue by clhodapp** [scala/pickling#101]
Sbt has some special handling for library dependencies under org.scala-lang. Of particular interest is the fact that it issues warnings if the versions of these libraries is not the same as scalaVersion in update. It's not pressing, but I hope that this issue will serve as a reminder that something really should be done about this.

**Comment by eed3si9n** [comment]
I don't think this happens with recent versions of sbt.
Are we talking about sbt/sbt#709?

**Comment by eed3si9n** [comment]
Actually sbt still has the code for [binaryScalaWarning](https://github.com/sbt/sbt/blob/v0.13.7/ivy/src/main/scala/sbt/IvyScala.scala#L65-L76), but Pickling 0.10.0 won't see it since it's now in a different organization. org.scala-lang.modules.

**Comment by retronym** [comment]
I'm getting the same issue now with the SBT build of Scala itself.

For now, I'm working around with:

```
// workaround for similar issue to https://github.com/scala/pickling/issues/101
val quietIvyLogging = ivyConfiguration := {
  val orig = ivyConfiguration.value.asInstanceOf[InlineIvyConfiguration]
  val origLogger = orig.log
  val filterLogger = new Logger {
    override def log(level: Level.Value, message: => String): Unit = {
      val msg = message
      val level1 = if (msg.contains("differs from Scala binary version in project")) Level.Debug else level
      origLogger.log(level1, msg)
    }

    override def success(message: => String): Unit = origLogger.success(message)

    override def trace(t: => Throwable): Unit = origLogger.trace(t)
  }
  new InlineIvyConfiguration(orig.paths, orig.resolvers, orig.otherResolvers, orig.moduleConfigurations, orig.localOnly, orig.lock, orig.checksums, orig.resolutionCacheDir, filterLogger)
}
```
