### ISSUE TITLE
Sonatype repo POM contains 2.10.2 dependencies

### ISSUE THREAD

**Issue by esorf** [scala/pickling#110]
scala-library & scala-reflect specify version 2.10.2 which leads to build warnings.

http://oss.sonatype.org/content/repositories/snapshots/org/scala-lang/scala-pickling_2.10/0.8.0-SNAPSHOT/scala-pickling_2.10-0.8.0-SNAPSHOT.pom

**Comment by eed3si9n** [comment]
Pickling depends on a specific version of scala-compiler. It's sort of the way it is.
