### ISSUE TITLE
deprecate for human, please

### ISSUE THREAD

**Issue by gaydenko** [scala/pickling#137]
Hi!

I have tried scala-pickling under 2.11.1 and have got deprecation warnings 
```
method normalize in class TypeApi is deprecated: Use `dealias` or `etaExpand` instead
```
against `pickle` and `unpickle` methods. Not sure where to find this message de-cyphering for "normal users". 

How to resolve the deprecation?

**Comment by eed3si9n** [comment]
I don't think this happens with Pickling 0.10.0 + Scala 2.11.x any more.
