### ISSUE TITLE
scalac freez  

### ISSUE THREAD

**Issue by omidb** [scala/pickling#145]
I am working with intellij, in both scala 2.11.0 and 2.10.4, no matter of what if I use .pickle I can not compile the code, no error, just freez in some points.
here is my code:

import scala.pickling._
import scala.pickling.binary._
val items = MyHelper.parseAll(MyHelper.getAllAtrAdjectives).pickle

**Comment by eed3si9n** [comment]
Could you try the latest Pickling 0.10.0 and if it still happens, please bring it up to IntelliJ guys.
