### ISSUE TITLE
Error: could not find implicit value for parameter e: scala.pickling.FastTypeTag

### ISSUE THREAD

**Issue by invkrh** [scala/pickling#158]
When testing pickling-0.8 with case class serialization, I got an error:
```scala
Error: could not find implicit value for parameter e: scala.pickling.FastTypeTag[Person]
```
I managed to do some workaround to get rid of it, but I am not sure it's a wanted feature.
Here are two code snippets will help to reproduce the error:

### Snippet 1:
```scala
object Test extends App {
	import scala.pickling._
	import json._
	case class Person(name: String, age: Int) // case class defined out of func test()
	def test() = {
		val res = Person("Hao", 10).pickle.value
		println(res)
	}
	test
}
```
This code is good and resulted in :
```json
{
  "tpe": "Test.Person",
  "name": "Hao",
  "age": 10
}
```
### Snippet 2:
```scala
object Test extends App {
	import scala.pickling._
	import json._
	def test() = {
		case class Person(name: String, age: Int) // case class defined in func test
		val res = Person("Hao", 10).pickle.value
		println(res)
	}
	test
}
```
This code resulted in an error:
```scala
[error] /home/invoker/workspace/scalacode/sbt-example-pickling/Test.scala:7: could not find implicit value for parameter e: scala.pickling.FastTypeTag[Person]
[error] 		val res = Person("Hao", 10).pickle.value
[error] 		                            ^
[error] one error found
```

I can not understand why the position of case class definition matters. At compile time, the implicit parameter value is erased ? Does it do with the scala Macro feature ? Could someone show me any deep insights ? Highly appreciate that.

Hao

**Comment by eed3si9n** [comment]
After changing to `import scala.pickling._, Defaults._` both cases works for me using Pickling 0.10.0.
