### ISSUE TITLE
Causes compile error in unrelated Java code.

### ISSUE THREAD

**Issue by cakoose** [scala/pickling#203]
I have a mixed Java and Scala project.  Using scala/pickling causes a compile error in a seemingly unrelated Java file.  Reduced test case:

Test.scala
```scala
case class Point(x: Int, y: Int)

object Test {
  import _root_.scala.pickling._
  import binary._
  // Comment this next line out, and the error in Unrelated.java goes away.
  def serialize(p: Point): Array[Byte] = p.pickle.value
}
```

Unrelated.java
```java
package serializers.xml;

public class Unrelated
{
	public static class Nested {};
	public static final Nested Nested = new Nested();  // error here
}
```

Compile output when I run `scalac` with both files together:
```
Unrelated.java:6: error: Nested is already defined as object Nested
	public static final Nested Nested = new Nested();
                                   ^
one error found
```

- Platform: Mac OS 10.9.4, Java 1.7.0_67, Scala 2.11.2
- Built scala/pickling from the latest source (0.9.x branch, commit 61d9f19)

**Comment by eed3si9n** [comment]
I was not able to reproduce this problem using Pickling 0.10.0.
