### ISSUE TITLE
invalid index 2 in unpicklee cache of length 2: json unpickling fails on second reference to same object

### ISSUE THREAD

**Issue by simbo1905** [scala/pickling#240]
Using: 

    "org.scala-lang" %% "scala-pickling" % "0.9.0",

Given:

    case class PaxosNumber(counter: Int, nodeIdentifier: Int)
    case class Identifier(val number: PaxosNumber, val logIndex: Long)
    case class Bookwork(val highestCommitted: Identifier, val highestPromised: PaxosNumber)

When: 

      import scala.pickling._
      import json._

      val minValue = PaxosNumber(Int.MinValue, Int.MinValue)
      val minBookwork = Bookwork(Identifier(minValue,0), minValue)
      val bytes = minBookwork.pickle.value
      System.err.println(new String(bytes))
      val parsed = bytes.unpickle[Bookwork]

Then:

      {
        "tpe": "com.github.simbo1905.trex.Bookwork",
        "highestCommitted": {
          "logIndex": "0",
          "number": {
            "counter": -2147483648,
            "nodeIdentifier": -2147483648
          }
        },
        "highestPromised": { "$ref": 2 }
      }
      fatal error: invalid index 2 in unpicklee cache of length 2
        at scala.pickling.CorePicklersUnpicklers$PrimitivePicklerUnpickler.unpickle(Custom.scala:389)

However this works: 

      val minBookwork = Bookwork(Identifier(PaxosNumber(Int.MinValue, Int.MinValue),0), PaxosNumber(Int.MinValue, Int.MinValue))
      val bytes = minBookwork.pickle.value
      System.err.println(new String(bytes))

      {
        "tpe": "com.github.simbo1905.trex.Bookwork",
        "highestCommitted": {
          "logIndex": "0",
          "number": {
            "counter": -2147483648,
            "nodeIdentifier": -2147483648
          }
        },
        "highestPromised": {
          "counter": -2147483648,
          "nodeIdentifier": -2147483648
        }
      }

So it looks like it attempting to create a pointer to the object as a form of compression but gets confused. It would be nice if I can disable that broken feature and if that can make it into the 9.1 release.

**Comment by jsuereth** [comment]
This appears to be fixed in master, and was most likely a bug in the generated code not mirroring the `shareOid` information in pickler/unpickler.
