### ISSUE TITLE
java.lang.OutOfMemoryError compiling a set of case classes

### ISSUE THREAD

**Issue by funkyjive** [scala/pickling#255]
I've been using scala pickling for a project and I have run into a compile time issue.  When I added a certain class structure of case classes (think of it as a tree structure), the compiler appears to go recursive and consume all the CPU and memory until the JVM dies with an OutOfMemoryError

I took my project code and reduced it to the smallest set I could that would reproduce the problem.  It did appear to run longer prior to the reduction of code (it seemed infinite to me), but potentially leaked slower.  Removing everything unecessary causes it to run out of memory much faster.  (Still takes a few minutes on my machine -- regardless it doesn't compile.)

So here is the code that reproduces the behavior on 0.9.1.  I have tried using both binary and fastbinary.  Will try json also just to be sure, but my hunch is that the problem is in base class stuff.

I know that if I comment out the encode/decode methods compilation is very fast -- because the pickle stuff doesn't get a chance to intervene and doing any object preparation.

```scala
case class ThingChild(nextThing : Thing, anotherThing : Option[Thing])
case class Thing (children : List[ThingChild])
case class ThingBox(mapByThingID : Map[Long,Thing])

trait BaseThingBoxContainer
case class ThingBoxContainer(thingMap : ThingBox)  extends BaseThingBoxContainer

object Pickler
{
  import scala.pickling._
  import fastbinary._
  def encode(m : BaseThingBoxContainer) : Array[Byte]  = m.pickle.value
  def decode(data : Array[Byte]) : BaseThingBoxContainer =   BinaryPickle(data).unpickle[BaseThingBoxContainer]
}
```

Don't know what I can change or do to make this work.

**Comment by eed3si9n** [comment]
I can't reproduce this using Pickling 0.10.0.
Here's the code with slight modification.

``` scala
case class ThingChild(nextThing : Thing, anotherThing : Option[Thing])
case class Thing (children : List[ThingChild])
case class ThingBox(mapByThingID : Map[Long,Thing])

trait BaseThingBoxContainer
case class ThingBoxContainer(thingMap : ThingBox)  extends BaseThingBoxContainer

object Pickler
{
  import scala.pickling._, Defaults._
  import binary._
  def encode(m : BaseThingBoxContainer) : Array[Byte]  = m.pickle.value
  def decode(data : Array[Byte]) : BaseThingBoxContainer =   BinaryPickle(data).unpickle[BaseThingBoxContainer]
}
```
