### ISSUE TITLE
Snapshot artifact seems to have vanished

### ISSUE THREAD

**Issue by manuelbernhardt** [scala/pickling#304]
The deep void at https://oss.sonatype.org/content/repositories/snapshots/org/scala-lang/modules/scala-pickling_2.11/ is glaring at me, almost as if annoyed by my presence.

**Comment by jsuereth** [comment]
as soon as you release a final, the -SNAPSHOT disappears.  We don't have a nightly build yet.

**Comment by manuelbernhardt** [comment]
So does it mean there should be no SNAPSHOT for `0.10.1`? I kind of assumed there would be one given what the last paragraph of `README.md` says.

**Comment by eed3si9n** [comment]
We should delete the section on SNAPSHOT from the README.

**Comment by phaller** [comment]
Actually, I found out why the SNAPSHOT is not published currently. It's a tiny bug in the Jenkins script. The (sub-) project names changed, but the Jenkins script was not updated. I'll fix it as soon as I get a chance.

**Comment by phaller** [comment]
I updated the jenkins scripts: https://github.com/scala/jenkins-scripts/pull/152

Thus, once #333 is merged, we can close this issue.

**Comment by phaller** [comment]
https://oss.sonatype.org/content/repositories/snapshots/org/scala-lang/modules/scala-pickling_2.11/0.10.2-SNAPSHOT/

**Comment by eed3si9n** [comment]
:+1:
