### ISSUE TITLE
Not production ready

### ISSUE THREAD

**Issue by Eilie** [scala/pickling#318]
It can't be production ready as long as it depends on unapply.
Usually in production you're dealing with large and old codebases and quite often case classes are holding more than 22 fields. 
Scala don't generate unapply for case classes with more than 22 fields.
Don't even try to blame me and existing architecture, I'm sick of it.

**Comment by eed3si9n** [comment]
@Eilie I could agree on your sentiment of production readiness, but >22 is not one of them in my criteria if it's caught statically. Do you mind renaming this case to something a bit more descriptive + supply repro steps so we can work on it? Thanks!

**Comment by Eilie** [comment]
Nevermind, I'm drunk and I love Scala.

**Comment by heathermiller** [comment]
Haha :laughing:
