### ISSUE TITLE
Runtime crash when pickling a FastTypeTag

### ISSUE THREAD

**Issue by emchristiansen** [scala/pickling#32]
Maybe it's a bit weird, but I want to serialize a FastTypeTag, so I can do type verification for a type-safe key-value store I hacked together.
Unfortunately, while the pickling seems to work, unpickling causes a runtime error.

## steps

This code:

    import scala.pickling._, Defaults._
    import scala.pickling.binary._

    val ftt = implicitly[FastTypeTag[Int]]
    val pickled = ftt.pickle
    // Crashes in this line.
    val unpickled = pickled.unpickle[FastTypeTag[Int]]

## problem

fails with this runtime error:

    [info]   scala.reflect.internal.MissingRequirementError: class $anon$1 not found.
    [info]   at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:16)
    [info]   at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:17)
    [info]   at scala.reflect.internal.Mirrors$RootsBase.ensureClassSymbol(Mirrors.scala:90)
    [info]   at scala.reflect.internal.Mirrors$RootsBase.staticClass(Mirrors.scala:119)
    [info]   at scala.reflect.internal.Mirrors$RootsBase.staticClass(Mirrors.scala:21)
    [info]   at scala.pickling.package$.typeFromString(package.scala:65)
    [info]   at scala.pickling.FastTypeTag$.apply(FastTags.scala:56)
    [info]   at scalatestextra.TestPersistentMap$$anonfun$1.apply$mcV$sp(testPersistentMap.scala:29)
    [info]   at scalatestextra.TestPersistentMap$$anonfun$1.apply(testPersistentMap.scala:26)
    [info]   at scalatestextra.TestPersistentMap$$anonfun$1.apply(testPersistentMap.scala:26)

**Comment by jsuereth** [comment]
@phaller I just pushed a brancht hat has a FastTypeTag provided pickler (works with runtime pickling too).  I'll add some tests and get it into 0.11.x.  cc @emchristiansen
