### ISSUE TITLE
Pickling hangs scalac phase typer

### ISSUE THREAD

**Issue by richard-jepps** [scala/pickling#326]
Using IntelliJ IDEA 14.1.2 and scala plugin 1.4.15 with scala 2.11.5:

```
Information:Using javac 1.8.0_05 to compile java sources
Information:24/04/2015 19:12 - Compilation completed with 1 error and 0 warnings in 20h 0m 56s 73ms
Error:scalac: Error: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
```

The phase typer hangs while processing a class that pickles an object graph to JSON. I'm relying on automatically generated picklers. The object graph starts with a WrappedArray[UnsealedTrait] and the instances contain values of various types including Array[Any]. 

I'm using the latest code from Git (commit e7249135ab0821c3c144b09ae9ffd52f996bdd2c). Note that scala-pickling 0.10.0 compiles quickly but loses most of the object graph on pickling. I couldn't pull the 0.10.1-SNAPSHOT from Sonatype and https://oss.sonatype.org/content/repositories/snapshots/org/scala-lang/modules/scala-pickling_2.11/ appears to be empty.

I have configured the Scala compile server with 6144MB and the Scala compiler with 4GB using the command line option -Jmx4G.

My project was originally converted to Scala using the IntelliJ Java to Scala conversion wizard. It contains about 19000 lines (including comments and blank lines) in 255 Scala files.

The compiler continued to run flat out (on up to 8 "cores") even after the error.

I've spent a lot of time tweaking my classes to be more Scala-friendly but it doesn't seem to have helped. Should pickling to JSON be able to deal with my use case?

Thank you

**Comment by eed3si9n** [comment]
> Should pickling to JSON be able to deal with my use case?

Without reproducible tests, it's hard to answer this. One thing you might try is try using it first Java 7 and without IntelliJ. Also I want to clarify that your pickler code compiled fine, and that you're seeing `OutOfMemoryError` while pickling some data.

We have seen `OutOfMemoryError` that I suspect is caused by Pickling too, and hopefully we can investigate more on it in the future.

**Comment by richard-jepps** [comment]
The OutOfMemoryError occurred after 20 hours. Despite the message the pickler code didn't finish compiling. The compiler continued running at between 600% and 800% of CPU (where 100% is one hyper thread running flat out) until I killed it.

I'll see if I get better results with Java 7 and post the result. Thank you.

**Comment by richard-jepps** [comment]
The code needed a few changes in order to compile and run on Java 7 from a shell script. These changes were: 1. remove dependencies on Java files in the project. 2. Increase the heap memory (8G was enough). 3. Solved runtime errors by removing the private modifier on two val members of a class to allow an Unpickler to be generated.

Incremental compilation via the IDE is reasonable after the first time, however initial compilation is still slow and so is full compilation via a shell script (1974 seconds). Using a shell script scalac -verbose seemed to spend a long time on org.postgis.Geometry. 

A lot of the members are either lost or pickled to abstract classes or 0 but I think these relate to known issues with Map, Array, Byte and Java classes.

**Comment by richard-jepps** [comment]
The answer to my question seems to be "No, scala-pickling to JSON does not currently support your use case. You might have more success by writing custom picklers for the cases where the generated picklers fail."
