### ISSUE TITLE
UUID values set to all zeros in unpicking, and custom case class byte arrays not what expected

### ISSUE THREAD

**Issue by helena** [scala/pickling#327]
I have a Type 1 UUID in my case class. pickling is doing this to the value:

original: 51662fe0-ecd8-11e4-934d-290c46447b11 
final uuid 00000000-0000-0000-0000-000000000000

```
import scala.pickling._,scala.pickling.Defaults._,scala.pickling.binary._
val pid = e.id.pickle.value
val uid = pid.unpickle[UUID]
```

What am I doing wrong? 
version "0.10.0"
scala 2.10.5 and 2.11.5 

Thanks

**Comment by eed3si9n** [comment]
This is a known issue with 0.10.0 reported originally as #122 and fixed in #123, but have not been released yet. The general unpickle asymmetry problem still stands and it's been discussed more in #295 and #296.

@jsuereth, @havocp, we should release 0.10.1.

**Comment by helena** [comment]
@eed3si9n @jsuereth @havocp  - Oh please release the next version if it does resolve the UUID issue. I need it for my Cassandra streaming solution, which I am hoping to release soon, but as it stands I had to back out my type-1 UUID (time-based UUID) id for each event due to this. I really want to keep using pickling for this solution:

https://datastax-oss.atlassian.net/browse/SPARKC-40
https://issues.apache.org/jira/browse/SPARK-6283

And I do wish there were more examples for library developers :)

**Comment by helena** [comment]
Hi @eed3si9n and @jsuereth, any ideas on a release date with the UUID fix?

**Comment by heathermiller** [comment]
Hi @helena – it appears it's already been released, but it seems we never updated the README or pinged you in this thread! Sorry. 

http://search.maven.org/#artifactdetails%7Corg.scala-lang.modules%7Cscala-pickling_2.11%7C0.10.1%7Cjar

http://search.maven.org/#search%7Cga%7C1%7Cscala-pickling

Can you let us know if you still have this issue after trying 0.10.1?

**Comment by helena** [comment]
@heathermiller thanks :) yes I didn't hit mvn repos, just checked the readme to see if it was released, thanks for the update! I'm psyched this made it in.

**Comment by dodnert** [comment]
I just updated my application - which is also having this problem - to version 0.10.1 and this problem does not seem to be resolved.

**Comment by eed3si9n** [comment]
@helena Sorry I missed the message above. 0.10.1 is out.

@dodnert It works for me as follows:

``` scala
scala> import scala.pickling._,scala.pickling.Defaults._,scala.pickling.binary._ 
import scala.pickling._
import scala.pickling.Defaults._
import scala.pickling.binary._

scala> import java.util.UUID
import java.util.UUID

scala> val id = UUID.randomUUID
id: java.util.UUID = 8ef3e994-9d88-4030-8012-9975b18fb67e

scala> val pkl = id.pickle
pkl: pickling.binary.pickleFormat.PickleType = BinaryPickle([0,0,0,14,106,97,118,97,46,117,116,105,108,46,85,85,73,68,-114,-13,-23,-108,-99,-120,64,48,-128,18,-103,117,-79,-113,-74,126])

scala> val obj = pkl.unpickle[UUID]
obj: java.util.UUID = 8ef3e994-9d88-4030-8012-9975b18fb67e
```

Please open an issue if this doesn't work for you.

**Comment by dodnert** [comment]
The issue I am seeing is that a `java.util.UUID` value is not pickled correctly if that value has been cast to a `scala.Any`. In my application, the value to be pickled is passed in to my application as an `Any` reference. Can this be made to work if the value is a `UUID`?

The code sequence below results in this output:
 {
   "$type": "java.util.UUID"
 }

```
val uuid = UUID.fromString("e3aa05c0-c771-11e4-b8a8-6146c4071e0f")
val p = uuid.asInstanceOf[Any].pickle.value
println(p)
```

**Comment by dodnert** [comment]
I've opened a new issue, #336 for the problem described in my previous comment.

**Comment by helena** [comment]
I tested with both type-1 UUID for timestamps and regular and it works, for instance:

import java.util.UUID

import scala.pickling._
import scala.pickling.Defaults._
import scala.pickling.binary._ 

def serialize(uuid: UUID): Array[Byte] = uuid.pickle.value
def deserialize[A: Unpickler: FastTypeTag](data: Array[Byte]): A = data.unpickle[A]

 "uuid roundtrip" in {
      val expected = UUID.randomUUID
      val ser = serialize(expected)
      val des = deserialize[UUID](ser)
      des should === (expected)
    }
    "type-1 uuid roundtrip" in { 
      val in = UUIDGen.getTimeUUID(now.getMillis)
      val ser = serialize(in)
      val des = deserialize[UUID](ser)
      des should === (in)
    }
