### ISSUE TITLE
Cannot generate an unpickler for error at compile time dependent on filename of source

### ISSUE THREAD

**Issue by NAJ10** [scala/pickling#338]
I've produced a reproducible test case where an unpickler cannot be generated for a case class. Oddly this error only manifests itself depending on what the name of the scala source class is called. Problem discovered in scala-pickling 0.10.1, scala 2.11.6 and sbt 0.13.8.

Set up three scala files with specific names and contents as follows
`src/main/scala/s/s/a/NodeInfo.scala`:

``` scala
package s.s.a
sealed abstract class NodeInfo {
}

final case class BNodeInfo (
                          h: String
                          ) extends NodeInfo

final case class SInfo  (
                          p: Boolean
                          ) extends NodeInfo
```

`src/main/scala/s/s/a/N.scala`:

``` scala
package s.s.a

import scala.pickling._
import scala.pickling.Defaults._
import scala.pickling.json._

object Helper {
  def fromJson(s: String) = JSONPickle(s).unpickle[NodeInfo]
}

src/main/scala/s/s/a/R.scala
package s.s.a

import scala.pickling._
import scala.pickling.Defaults._
import scala.pickling.json._

object RHelper {
  def fromJson(s: String) = JSONPickle(s).unpickle[NodeInfo]
}
```

The code in the Helper and RHelper objects are identical apart from the name of the object yet the RHelper one compiles and the Helper one does not. If you rename N.scala to S.scala the problem goes away. If you then rename S.scala back to N.scala and R.scala to B.scala you get two compilation errors instead of one.

**Comment by jsuereth** [comment]
@NAJ10 What you've found is actually the issue we have with the order in which the compiler reads source-files AND the ability of pickling to find known subclasses.   I just ran a quick test locally.   If you use the `@directSubclasses` annotation you should be able to avoid this scenario by forcing the compiler to load the subclass symbols for NodeInfo when it's generating the pickler in `N.scala`.    In the 0.11.x branch we've added a few more error messages to help guide users in the usage of the `@directSubclasses` annotation to work around this issue.

Unfortunately, it's not something we can fix on the pickling side.  It's also probably not a feature we should rely on in the compiler, but at least there is a workaround now.  Hope that helps!
