### ISSUE TITLE
Pickling List(1,2,3) into JSON should produce a JSON array

### ISSUE THREAD

**Issue by backuitist** [scala/pickling#346]
I've just ran the following snippet from the documentation:

```
    import scala.pickling._
    import json._

    val pckl = List(1, 2, 3).pickle    
    println(pckl)
```

Which produces

```
JSONPickle({
  "$type": "scala.collection.immutable.$colon$colon[scala.Int]",
  "head": 1,
  "tl": {
    "$type": "scala.collection.immutable.$colon$colon[scala.Int]",
    "head": 2,
    "tl": {
      "$type": "scala.collection.immutable.$colon$colon[scala.Int]",
      "head": 3,
      "tl": {
        "$type": "scala.collection.immutable.Nil.type"
      }
    }
  }
})
```

What the hell?

Even worse:

```
    (1 to 1000).toList.pickle
```

Gives me a `java.lang.StackOverflowError`

**Comment by eed3si9n** [comment]
Scala pickling's default JSON format prioritizes keeping the type info around and runtime performance.
If you want prettier JSON format, checkout sbt's serialization that's built on top of Pickling - https://github.com/sbt/serialization

**Comment by backuitist** [comment]
I can't see how this has a better runtime performance than `[1,2,3]`? Plus as you might have skipped the bottom of the issue `(1 to 1000).toList.pickle` performs so badly that it gives up in a StackOverflowError.

Now back to the type info, you're point is that this representation allows one to unpickle Any and be sure to get a List[Int], and not, say a Vector[Int]?

Having to resort to a third party library to get just that is.... surprising to the least.

**Comment by jsuereth** [comment]
@backuitist The 0.11.x branch has a custom List[_] pikler now which should dramatically improve the performance of list pickling (in my quick tests).
