### ISSUE TITLE
Pickling will generate pickler sometimes

### ISSUE THREAD

**Issue by raam86** [scala/pickling#350]
I ran into an issue where I run code and a pickler is generated.
after changing unrelated piece of code in the same project will break the build saying 

```
Cannot generate a pickler for com.apester.streamingHttp.etl.Models.Event. Recompile with -Xlog-implicits for details
[error]     e.pickle
```

(e is an instance of Event)

changing in code `e.pickle` to `e.picklee.pickle` will compile again. 

I tried reproducing with a simple case but to no avail.

running  -Xlog-implicits
didn't show any meaningful error (to me)

```
[info] /Users/raam/Code/suggest-flow/modules/httpstream-flow/src/main/scala/com.apester.streamingHttp/etl/serialize/pickel.scala:24: genPickler is not a valid implicit value for scala.pickling.Pickler[com.apester.streamingHttp.etl.Models.Event] because:
[info] hasMatchingSymbol reported error: stepping aside: repeating itself
[info]     e.pickle
```

I am compiling with SBT. is there any chance this is happening because of incremental builds?

**Comment by jsuereth** [comment]
There is a chance that is why it's occuring. 

Pickling has some known issues with visibility of classes in the compiler.  Sometimes the macros will fail because during incrmeental compilation not all the subclasses are loaded, e.g.   We have some workaround to fix it, but it may be easier to diagnose if you can show us what `Event` looks like (hierarchy).

**Comment by raam86** [comment]
```
  sealed case class Event(id:UUID,`type`:String,timestamp:DateTime,hour_timebucket:DateTime,props:EventDetails)
  case class EventDetails(properties:List[EventProp],interaction_id:String,session_id:String)
  sealed abstract class EventProp
  case class numberProp(label:String,content:Int) extends EventProp
  case class stringProp(label:String,content:String) extends EventProp
```
