### ISSUE TITLE
`hintTag` should be optional, or not a `hint`

### ISSUE THREAD

**Issue by jsuereth** [scala/pickling#359]
Currently, all picklers/unpicklers are required to `hintTag`.   Additonally, they can `hintStaticallyElided` and other such 'fun'.

While we _do_ need `tag` support built in to handle subclassing/enum-like picklers, we should adjust how we handle tagging/eliding so that people know the tag is not optional.

My proposal:
1. `PBuilder.beginEntry` is updated to be:
    `def beginEntry(picklee: Any, tag: FastTypeTag[_]): Unit`
2. `hintStaticallyElided`/`hintDynamicallyElided` work as before when pickling, except they are altered to be:
   ``def hintElidedType(tag: FastTypeTag[_]): Unit`
3. Picklers/Unpicklers are no longer required to call `hintTag`
4. If a Pickler used an elide hint, the unpickler must also
5. `hintTag` disappears from the API.

**Comment by eed3si9n** [comment]
What about `PickleContext` as the new name? We just need a name which we push/pop/pin etc. and that stuff has has-a relationship with `FastTypeTag` and `size: Int`?

**Comment by jsuereth** [comment]
The new name of what?   Hints are defined directly on the PBuilder/PReader.  

Additionally, the thing which `hintElidedType` is NOT the thing which does the pickling/unpickling, it's generally the container.

e.g. `case class Foo(x: Int, y: Bar)` the pickler for `Foo` would be the one who provides the elide hints before pickling `x`.   The raw `x` pickler actually needs to emit the type tag because you could potentially unpickle to an `Any`,

So, without a bit more context, not sure what you mean by `PickleContext`

**Comment by jsuereth** [comment]
So I attached an implementation.  Surprisingly easy to accomplish, which I think means it's the right direction for simplification.

**Comment by eed3si9n** [comment]
> The new name of what? Hints are defined directly on the PBuilder/PReader.

`PickleContext` represents a data structure of stuff that gets hinted by outer builder/reader via `Hintable`.
Eliding (or not eliding) should a decision given to each format, not the pickler. For example, for growable JSON, I don't want to include type tag into all JSON object. If you're building a fast binary format, and don't care about growability you could pack your binary with `Int` and `Bar` without any tags.

**Comment by jsuereth** [comment]
@eed3si9n That's actually a different matter entirely, and you should open a ticket about that.

I think a lot of things fall apart if we try to make tags optional everywhere.   What I'm trying to do is dramtically improve the elide situation, while I continue thinking of ways to make tag completely optional by-format.   Would most likely require `beginEntry` in PReader to also take in an `expectedTag`, but I worry that tag-related behavior is something the pickler needs to execute on, not the format.   That's one of those situations where things are blurry but we may be able to keep a clean separation and get you what you want.  Still, I think it merits its own ticket/enhancement request.

(Note: This ticket comes with a working implementation :) ).

**Comment by jsuereth** [comment]
Fixed by #362
