### ISSUE TITLE
Scala, file name too long, compile crashes

### ISSUE THREAD

**Issue by vboilay** [scala/pickling#392]
Hi, there are already many posts about that.
I use windows, compiler crash probably for the same reason while the error message is different:
"The filename, directory name, or volume label syntax is incorrect"
from sbt, compile sometimes crashes, sometimes not.
From from IntelliJ (2016.1), it crashes every time.
No encrypted drive.
That is very very ennoying almost a showstopper for me :-(
Has this been taken into account for the new build (I got 0.10.1, scala version 2.10.5 sbt version 0.13.8) ?
many thanks in advance.

**Comment by jvican** [comment]
This seems to be a scala compiler-related problem, the good place to report this would be here: https://github.com/scala/scala

**Comment by jsuereth** [comment]
This is related to the scala 2.10.x compiler, you can see how we work aorund it here:

https://github.com/scala/pickling/blob/0.11.x/build.sbt#L12

Hope that helps!
