### ISSUE TITLE
How to remove hint information from picklers in scala-pickling 0.11.x ?

### ISSUE THREAD

**Issue by hordon** [scala/pickling#404]
I just want to serialize case class to simple json like that:

``` scala
object Test extends App {
  val pickle = Person("Lisa", "Daniels").pickle
  val jsonString = pickle.value // I expect {"firstName":"Lisa","lastName":"Daniels"}
  val person = jsonString.unpickle[Person]
}
```

In reality jsonString contains `{"$type":"Person","firstName":"Lisa","lastName":"Daniels"}`
I would like to exclude `$type` attribute from resulting json.

While discovering library source code i found that `$type` can be removed from json by way passing hint to `JSONPickleBuilder`.

In pickling version 0.10.x it can be achieved by simply invoking `hintStaticallyElidedType()` but in 0.11.x this method was replaced with `hintElidedType(tag: FastTypeTag[_])` - now it receives tag of case class that we want to serialize.

To solve this issue i tried to send a hint to `JSONPickleBuilder`:

``` scala
object serialization extends JsonFormats with Ops with AllPicklers {

  class CustomJSONPickleBuilder(format: JSONPickleFormat, buf: Output[String]) extends JSONPickleBuilder(format, buf) {
    override def beginEntry(picklee: Any, tag: FastTypeTag[_]): PBuilder = {
      hintElidedType(tag)
      super.beginEntry(picklee, tag)
      this
    }
  }

  override implicit val pickleFormat: JSONPickleFormat = new JSONPickleFormat {
    override def createBuilder() = new CustomJSONPickleBuilder(this, new StringOutput)
    override def createBuilder(out: Output[String]): PBuilder = new CustomJSONPickleBuilder(this, out)
  }

  implicit val staticOnly = static.StaticOnly
}
```

Now it serializes fine but when i call `val person = jsonString.unpickle[Person]` it throws an exception `scala.pickling.PicklingException: Logic pickling error:  Could not find a type tag, and no elided type was hinted: Map(firstName -> Lisa, lastName -> Daniels)`
I think that it because i should send a hint to not only to `JSONPickleBuilder` but also to `JSONPickleReader`, but i don't know how to do that, because neither method from JSONPickleReader receive `FastTypeTag[_]` to its argument.

How can i elegantly pass hints to `JSONPickleReader` and `JSONPickleBuilder` in order to remove hint information from picklers ?

**Comment by jvican** [comment]
Yes. You're getting this error because you don't have a `CustomJsonUnpickler`. If you elide the type, you have to make sure that you also elide the type when you unpickle (via `hintElidedType`). If you don't, you get this error because scala pickling is looking for a type in the json message.

To solve this problem, do the same you've done for `Builder` but now for the `Reader`.

**Comment by hordon** [comment]
For some hours i found the solution. It's a little bit tricky to remove hint information. I think it should be more simple because it takes some time to understand the internals of the library and do that work.

``` scala
import scala.pickling._
import scala.pickling.json.{JSONPickle, JSONPickleBuilder, JSONPickleFormat}
import scala.pickling.pickler.AllPicklers

object serialization extends AllPicklers {

  private final class CustomJSONPickleFormat(tag: FastTypeTag[_]) extends JSONPickleFormat {

    private def setHints(h: Hintable) {
      h.hintElidedType(tag)
    }

    override def createBuilder(): JSONPickleBuilder = {
      val b = super.createBuilder()
      setHints(b)
      b
    }
    override def createBuilder(out: Output[String]): PBuilder = {
      val b = super.createBuilder(out)
      setHints(b)
      b
    }
    override def createReader(pickle: JSONPickle): PReader = {
      val b = super.createReader(pickle)
      setHints(b)
      b
    }
  }

  implicit final class EncodeDecodeOps[T](picklee: T) {
    def encode(implicit pickler: Pickler[T]): String = {
      val pickleFormat = new CustomJSONPickleFormat(pickler.tag)
      functions.pickle(picklee)(pickleFormat, pickler).value
    }

    def decode[A](implicit c: T => String, unpickler: Unpickler[A]): A = {
      val pickleFormat = new CustomJSONPickleFormat(unpickler.tag)
      functions.unpickle[A](json.JSONPickle(picklee))(unpickler, pickleFormat)
    }
  }
}
```

**Comment by jvican** [comment]
I agree that it should be easier to do. I'd make a PR making it easy.
