### ISSUE TITLE
generic function with pickling

### ISSUE THREAD

**Issue by mateuszdraco** [scala/pickling#41]
Is it possible to write generic function that would pickle given argument of yet unknown type?
Something like:

```scala
object Barrel {
    def put[A](objx: A) = objx.pickle.value
    def get[A](valx: String) = valx.unpickle[A]
}
```

**Comment by jsuereth** [comment]
@mateuszdraco FYI - I think you only need to import `json._` at the Barrel implementation site.  IN any case, We are actively doing this in sbt-serialization, see: https://github.com/sbt/serialization/blob/master/serialization/src/main/scala/sbt/serialization/SerializedValue.scala#L23

Going to close this for now, please re-open if you see issues on master.
