### ISSUE TITLE
Add ability to unpickle from a file (we can already pickle to a file..., why not from?)

### ISSUE THREAD

**Issue by heathermiller** [scala/pickling#43]
In #5 we introduced support for pickling to files, but for some reason we neglected add support for _unpickling from_ files.

**Comment by colin-scott** [comment]
Hi, can someone provide an example of unpickling from a text (json) file? Thanks!

**Comment by siddhartha-chandra** [comment]
Hi, 
Please can you provide with an example of unpickling from a file. I have created a pickle file using the 0.9.x. branch (0.8-snapshot somehow fails for me) and using 'TextFileOutput' instead of 'BinaryFileEncodedOutput' (unable to figure out where this resides). Currently, I need help in unpickling from the saved file (the 'FilePickle' class that you mentioned; I'm unable to locate it). Please can you provide some pointers. Appreciate your help! Thanks!

**Comment by trumanw** [comment]
Here is an example of unpickling from a file:

``` scala
class Brotherhood(
    var name: String, 
    var brothers: Option[Seq[Brotherhood]])

def pickleTo(brothers: Brotherhood, filename: String) = {
        // convert to Pickle binary object
        val brothersPickle = brothers.pickle
        // get the pickle bytes array
        val brothersPickleByteArray = brothersPickle.value
        // write bytes array into the file 
        val fos = new FileOutputStream("./" + filename)
        fos.write(brothersPickleByteArray)
        fos.close
}

def unpickleFrom(filename: String): Brotherhood = {
        val brothersRawFromFile = scala.io.Source.fromFile("./" + filename).map(_.toByte).toArray
        val brothersUnpickleValue = BinaryPickle(brothersRawFromFile)
        val brothersUnpickle = brothersUnpickleValue.unpickle[Brotherhood]
        brothersUnpickle
}

object SerializationDemo extends App {
    val tom = new Brotherhood("Tom", None)
    val smith = new Brotherhood("Smith", None)
    val richard = new Brotherhood("Richard", None)
    val brothers = new Brotherhood("Assassin", Option(Seq(tom, smith, richard)))

    pickleTo(brothers, "PickleBinaryFile")
    val brotherhoodUnpickle = unpickleFrom("PickleBinaryFile")
}
```

The source code is on my [gist](https://gist.github.com/TrumanWu/c56e257f0bbc9b1d8e6a)

**Comment by siddhartha-chandra** [comment]
Thanks @TrumanWu ! Your response was vital in solving my issue and the example you gave couldn't have been more lucid. Now I am able to pickle to a file and unpickle from it :)

Though, there is one thing I would like to point out in the 'unpickleFrom' function.
I had to explicitly specify the 'codec' name while reading from the file. I think the default codec is different for different systems. So essentially replaced:
"val brothersRawFromFile = scala.io.Source.fromFile("./" + filename).map(_.toByte).toArray"
with
val brothersRawFromFile = scala.io.Source.fromFile("./" + filename,  "iso-8859-1").map(_.toByte).toArray

Rest, it worked seamlessly :) 
Thanks again!

**Comment by MishaelRosenthal** [comment]
How would I go about doing the same for an Iterator (stream) of elements?
Namely, instead of writing an element or a sequence of elements, I want to write them from an iterator.
Then read them iteratively too? 

I want to do so since I do not have enough memory to materialize them.

**Comment by sc6l6d3v** [comment]
Hi,

Am having some issues with the above gist from trumanw:

https://gist.github.com/nanothermite/871c4dc0e452c5ddca94436422e34804

With this build.sbt:

lazy val pickling = "org.scala-lang" %% "scala-pickling" % "0.9.1"

lazy val root = (project in file(".")).
  settings(
    name := "sbt-pickling-example",
    scalaVersion := "2.11.5",
    libraryDependencies += pickling,
    resolvers += Resolver.sonatypeRepo("snapshots")
  )

I am seeing this exception thrown:

/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/bin/java -Didea.launcher.port=7538 "-Didea.launcher.bin.path=/Applications/IntelliJ IDEA.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/lib/tools.jar:/Users/hkatz/workspaces/DataScience/sbt-example-pickling/target/scala-2.11/classes:/Users/hkatz/.ivy2/cache/org.scala-lang/scala-compiler/jars/scala-compiler-2.11.4.jar:/Users/hkatz/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.2.jar:/Users/hkatz/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.11/bundles/scala-parser-combinators_2.11-1.0.2.jar:/Users/hkatz/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.4.jar:/Users/hkatz/.ivy2/cache/org.scala-lang/scala-pickling_2.11/jars/scala-pickling_2.11-0.9.1.jar:/Users/hkatz/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.5.jar:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar" com.intellij.rt.execution.application.AppMain SerializationDemo
Exception in thread "main" java.lang.ClassCastException: scala.pickling.fastbinary.BinaryPickleArray cannot be cast to scala.pickling.json.JSONPickle
    at scala.pickling.json.JSONPickleFormat.createReader(JSONPickleFormat.scala:23)
    at Brotherhood$.unpickleFrom(SerializationDemo.scala:31)
    at SerializationDemo$.delayedEndpoint$SerializationDemo$1(SerializationDemo.scala:45)
    at SerializationDemo$delayedInit$body.apply(SerializationDemo.scala:37)
    at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
    at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
    at scala.App$$anonfun$main$1.apply(App.scala:76)
    at scala.App$$anonfun$main$1.apply(App.scala:76)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
    at scala.App$class.main(App.scala:76)
    at SerializationDemo$.main(SerializationDemo.scala:37)
    at SerializationDemo.main(SerializationDemo.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

Process finished with exit code 1

Still debugging - it's a macro - quite challenging. Any suggestions?

Thanks,
Henry

**Comment by sc6l6d3v** [comment]
Never mind - figured it out:

https://gist.github.com/nanothermite/651c52b4161aee8742fc2e250c8729a3
