### ISSUE TITLE
Cut first milestone release

### ISSUE THREAD

**Issue by jvican** [scala/pickling#431]
It would be interesting to start publishing what we have for the `0.11.0` release.

**Comment by heathermiller** [comment]
Let me know when to cut it and I can take care of it.

**Comment by jvican** [comment]
After https://github.com/scala/pickling/issues/432 is merged, could you cut `0.11.0-M1` @heathermiller? :smile:

**Comment by heathermiller** [comment]
Sure

**Comment by jvican** [comment]
Actually, after this https://github.com/scala/pickling/pull/434 that correctly sets the version.

**Comment by jvican** [comment]
@heathermiller you can cut the release now, master's been updated! :dancer:

**Comment by heathermiller** [comment]
Ok, `0.11.0-M2` it is. Gimme an hour or two and I'll take care of it

**Comment by phaller** [comment]
Wow, @jvican has a strong emoji game! :-)

**Comment by heathermiller** [comment]
@jvican can you start preparing release notes for 0.11.x?

**Comment by jvican** [comment]
There's still some ongoing work that needs to go into `0.11.x`, so I'd rather write the release notes when everything is ready for the final release, and not the milestone. However, @jsuereth has some release notes here: https://github.com/scala/pickling/blob/0.11.x/notes/0.11.0.markdown.

**Comment by heathermiller** [comment]
Normally, minutes are a work-in-progress. People add to the minutes as they make changes to a release. It's a lot easier to iteratively add new lines than to try and remember at the last minute before cutting the release all the stuff that was added/changed.

So I would really encourage you to add to Josh's notes if you can. It'd help you/us down the line on the final release notes, and others who might be watching the project.

**Comment by jvican** [comment]
Right, I'll get down to it soon then!

**Comment by heathermiller** [comment]
Release cut. It normally takes a couple of hours to propagate, but when it's available you should be able to see it here:
http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.scala-lang.modules%22%20AND%20a%3A%22scala-pickling_2.11%22

**Comment by heathermiller** [comment]
Now live!: http://search.maven.org/#artifactdetails%7Corg.scala-lang.modules%7Cscala-pickling_2.11%7C0.11.0-M2%7Cjar
